services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:8000"
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/