# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Copy the rest of the application files
COPY . .

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run the command to start the flask app
CMD ["python", "web.py"]
